name: KAM Sentinel - Test & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask psutil GPUtil pyinstaller

    - name: Run test suite
      run: python test_kam.py
      
    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: test_report.html

    - name: Build EXE
      if: github.ref == 'refs/heads/main'
      run: |
        python -m PyInstaller --name "KAM_Sentinel" --onefile --noconsole `
          --add-data "dashboard.html;." `
          --add-data "thresholds.py;." `
          --hidden-import flask `
          --hidden-import psutil `
          --hidden-import GPUtil `
          launch.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main'
      with:
        name: KAM_Sentinel-${{ github.sha }}
        path: dist/KAM_Sentinel.exe
        retention-days: 30

    - name: Get version
      id: version
      run: |
        $ver = python -c "import json; print(json.load(open('version.json'))['version'])"
        echo "version=$ver" >> $env:GITHUB_OUTPUT

    - name: Create Release on version tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/KAM_Sentinel.exe
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
